# Dictionary of stock tickers and their corresponding company names, categorized by industry sector. Each key in the outer dictionary represents an industry sector, and the value is another dictionary that maps stock tickers to their full company names.

TICKERS = {
    "Commercial Banks": {
        "HBL": "Habib Bank Limited",
        "UBL": "United Bank Limited",
        "BAFL": "Bank Alfalah Limited",
        "MCB": "MCB Bank Limited",
        "ABL": "Allied Bank Limited",
        "MEBL": "Meezan Bank Limited",
        "NBP": "National Bank of Pakistan",
        "SCBPL": "Standard Chartered Bank (Pakistan)",
        "BAHL": "Bank Al Habib Limited",
        "AKBL": "Askari Bank Limited",
        "FABL": "Faysal Bank Limited",
        "HMB": "Habib Metropolitan Bank Limited",
        "BOP": "Bank of Punjab",
        "SBL": "Samba Bank Limited",
    },
    "Oil & Gas Exploration Companies": {
        "OGDC": "Oil & Gas Development Company",
        "PPL": "Pakistan Petroleum Limited",
        "MARI": "Mari Petroleum Company",
        "PSO": "Pakistan State Oil",
        "SNGP": "Sui Northern Gas Pipelines",
        "POL": "Pakistan Oilfields Limited",
    },
    "Food & Personal Care Products": {
        "NESTLE": "Nestle Pakistan Limited",
        "COLG": "Colgate-Palmolive (Pakistan) Limited",
        "UPFL": "Unilever Pakistan Foods Limited",
        "ISIL": "Ismail Industries Limited",
        "NATF": "National Foods Limited",
        "FFL" : "Fauji Foods Limited",
        "RMPL": "Rafhan Maize Products Company Limited",
        "FCEPL": "FrieslandCampina Engro Pakistan Limited",
        "MUREB": "Murree Brewery Company Limited",
        "GLPL": "Gillette Pakistan Limited",
        "TREET": "Treet Corporation Limited",
        "UNITY": "Unity Foods Limited",
        "PREMA": "At-Tahur Limited",
    },
    "Pharmaceuticals": {
        "GLAXO": "GlaxoSmithKline Pakistan Limited",
        "ABOT": "Abbott Pakistan Limited",
        "HALEON": "Haleon Pakistan Limited",
        "HINOON": "Highnoon Laboratories Limited",
        "SEARL": "Searle Company Limited",
        "AGP": "AGP Limited",
        "HPL": "Hoescht Pakistan Limited",
        "CPHL": "Citi Pharma Limited",
        "FEROZ": "Ferozsons Laboratories Limited",
    },
    "Engineering": {
        "ISL": "International Steels Limited",
        "MUGHAL": "Mughal Iron & Steel Industries Limited",
        "INIL": "International Industries Limited",
        "ASL": "Aisha Steel Mills Limited",
        "BECO": "Beco Steel Limited",
        "PECO": "Pakistan Engineering Company Limited",
        "MUGHALC": "Mughal Iron & Steel Industries Limited (Cement Division)",
        "DADX": "Dadex Eternit Limited",
        "MSCL": "Metropolitan Steel Corporation Limited",
        "ITTEFAQ": "Ittefaq Iron Industries Limited",
    },
    "Insurance": {
        "EFUL": "EFU Life Assurance Limited",
        "JLICL": "Jubilee Life Insurance Company Limited",
        "AICL": "Adamjee Insurance Company Limited",
        "JGICL": "Jubilee General Insurance Company Limited",
        "PAKRI": "Pakistan Reinsurance Company Limited",
        "TPLI": "TPL Insurance Limited",
        "PKGI": "The Pakistan General Insurance Company Limited",
        "ALAC": "Askari Life Assurance Company Limited",
        "PQGTL": "Pak-Qatar General Takaful Limited",
    },
    "Cement": {
        "LUCK": "Lucky Cement Limited",
        "DGKC": "D.G. Khan Cement Company",
        "MLCF": "Maple Leaf Cement Factory",
        "THCCL": "Thatta Cement Company",
        "BWCL": "Bestway Cement Limited",
        "FCCL": "Fauji Cement Company Limited",
        "KOHC": "Kohat Cement Company",
        "PIOC": "Pioneer Cement Limited",
        "CHCC": "Cherat Cement Company",
        "ACPL": "Attock Cement Pakistan Limited",
        "POWER": "Power Cement Limited",
        "DCL": "Dewan Cement Limited",
    },
    "Fertilizer": {
        "FFC": "Fauji Fertilizer Company",
        "AHCL": "Arif Habib Corporation Limited",
        "FFBL": "Fauji Fertilizer Bin Qasim Limited",
        "EFERT": "Engro Fertilizers Limited",
        "FATIMA": "Fatima Fertilizer Company Limited",
        "AGL": "Agritech Limited",
    },
    "Power Generation & Distribution": {
        "HUBC": "Hub Power Company",
        "KEL": "K-Electric Limited",
        "KAPCO": "Kot Addu Power Company",
        "NPL": "Nishat Power Limited",
        "NCPL": "Nishat Chunian Power Limited",
        "PKGP": "Pakgen Power Limited",
        "GEMMEL": "Mughal Energy Limited (GEM)",
        "EPQL": "Engro Powergen Qadirpur Limited",
        "SGPL": "S.G. Power Limited",
    },
    "Technology": {
        "SYS": "Systems Limited",
        "TRG": "TRG Pakistan Limited",
        "NETSOL": "NetSol Technologies",
        "PTC": "Pakistan Telecommunication Company Limited",
        "AIRLINK": "Airlink Communication Ltd",
        "SELECT": "Select Technologies (Pvt) Ltd",
        "AVN": "Avanceon Limited",
        "HUMNL": "Hum Network Limited",
        "MDTL": "Media Times Limited",
        "TPL": "TPL Corp Limited",
        "TELE": "Telecard Limited",
    },
    "Automobile": {
        "INDU": "Indus Motor Company",
        "SAZEW": "Sazgar Engineering Works",
        "HCAR": "Honda Atlas Cars (Pakistan)",
        "SLM": "Service Long March Tyres Limited",
        "THALL": "Thal Limited",
        "TBL": "Treet Battery Limited",
        "PTL": "Panther Tyres Limited",
        "ATBA": "Atlas Battery Limited",
        "EXIDE": "Exide Pakistan Limited",
        "BWHL": "Baluchistan Wheels Limited",
        "ATLH": "Atlas Honda Limited",
        "MTL": "Millat Tractors Limited",
        "GHNI": "Ghandhara Industries Limited",
        "GAL": "Ghandhara Automobiles Limited",

    },
    "Inv. Banks / Inv. Cos. / Securities Cos.": {
        "PSX": "Pakistan Stock Exchange",
        "ENGROH": "Engro Holdings Limited",
        "PIAHCLA": "PIA Holding Company Limited",
        "DLL": "Dawood Lawrencepur Limited",
        "IMS": "Intermarket Securities Limited",
        "AKDSL": "AKD Securities Limited",
        "MCBIM": "MCB Investment Management Limited",
        "AHL": "Arif Habib Limited",
        "OLPL": "OLP Financial Services Limited",
        "LSEVL": "LSE Ventures Limited",
        "JSGCL": "JS Global Capital Limited",
        "FNEL": "First National Equities Limited",
        "CYAN": "Cyan Limited",
        "JSIL": "JS Investments Limited",
        "LSECL": "LSE Capital Limited",
        "FCIBL": "First Credit and Investment Bank Limited",
        "TSBL": "Trust Securities & Brokerage Limited",
    },
}